[package]
name = "robomaster-s1-proto"
version = "0.1.0"
edition = "2021"
author = "Fan Jiang"
license = "MIT OR Apache-2.0"

[dependencies]
bytemuck = { version = "1.16.*", features = ["derive"] }

[dev-dependencies]
clap = { version = "4.5.13", features = ["derive"] }
chumsky = "*"
